config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
      root to: 'top#home'
      get "about" => "top#about", as: "about"
      post 'top/confirm' => 'top#confirm' #確認画面
      post 'top/thanks' => 'top#thanks' #送信完了画面
      get "terms_of_service" => "top#terms_of_service"
      
      get 'users/me' => 'users#me'
      get '/users/:user_id/show', to: 'users#show', as: 'show_user'
      delete 'delete_users/:id' => 'users#destroy', as: :delete_user
      
      get 'events/:event_id/show', to: 'events#show', as: 'show_event'
      
      scope :organizer do
        resources :events, except: [:show, :index] do
          member do
           post 'confirm', to: 'events#confirm'
           post 'confirm2', to: 'events#confirm2'
          end
        end
        resources :timetables
      end
      
      resources :blogs, except: [:index, :show]
      get 'blogs/:blog_id/show', to: 'blogs#show', as: 'show_blog'
      
      get "organizer/blogs" => "users#blogs", as: "postblog"
      get "organizer/else" => "users#elses", as: "else"
      
      scope :admin do
        resources :events, except: [:show, :index] do
          member do
            post 'confirm2'
          end
        end
        post 'events/confirm', to: 'events#confirm'
        # post 'events/confirm2', to: 'events#confirm2'
        resources :timetables
      end
      
      get 'admin/dashboard'
      get 'admin/users'
      get 'admin/events'
      get 'admin/events/:event_id/participants', to: 'admin#participants', as: 'admin_participants'
      
      resources :events, only: [:show, :index] do
        member do
          get "ticket" => "events#ticket"
        end
        resource :bookings, only: [:create, :destroy]
        member do
          get "charge" => "bookings#charge"
          post "pay" => "bookings#pay"
        end
      end
      
  end
  
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  
end

app/models/top.rb
class Top include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, length: { maximum: 20 } , presence: true
  validates :email, length: { maximum: 30 } , presence: true
  validates :message , length: { maximum: 50 } , presence: true
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  #layout "top_layout"
  
  def home
    @events = Event.all
    @blogs = Blog.all
    render :home, layout: "top_layout"
  end
  
  def about
    @top = Top.new
  end
  
  def confirm
    @top = Top.new(top_params)
    if @top.valid?
      render :action => 'confirm'
    else
      render :action => 'about'
    end
  end
  
  def thanks
    @top = Top.new(top_params)
    TopMailer.received_email(@top).deliver
    render :action => 'thanks'
  end
  
  def terms_of_service
  end
  
  private
  def top_params
    params.require(:top).permit(:name, :email, :message)
  end
  
end

app/views/top/about.html.erb
<% @page_title = "About" %>

<div class="inquiry-header">About English Rakugo</div>

    <div class="img-responsive jumbotron">
      <div class="about-text">
        <h1>this is test</h1>
      </div>
    </div>
    
<div class='row outline'>
  <div class="inquiry-header">Company Outline</div>
    <div class='col-sm-offset-2 col-sm-8'>
   　<table class="table">
        <tr>
          <th>Company Name</th>
          <td>NPO Kobe Travellers Club</td>
        </tr>
        <tr>
          <th>Headquarters</th>
          <td>Morikitamachi 4-8-23 Higashinada Kobe 
              Hyogo 658-0001 Japan
          </td>
        </tr>
        <tr>
          <th>Representative Director</th>
          <td>Hisao Hirako</td>
        </tr>
        <tr>
          <th>Our Vision</th>
          <td>The communities that form through events support people both personally and professionally. 
              We want to make it easier for event organizers to grow these communities, 
              and encourage participants to get further involved in them.
          </td>
        </tr>
        <tr>
          <th>History</th>
          <td>July 2010	&nbsp;First public release of _____<br />
              June 2013	&nbsp;_____ Inc established
          </td>
        </tr>
        <tr>
          <th></th>
          <td></td>
        </tr>
      </table>
    </div>
</div>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div id="inquiry" class="inquiry-header">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Contact Us
    </div>
    <div class="contact-message">Send us your questions or comments about us.</div>
    <div class="contact-message">We value your questions and comments.</div>
    <div class="card card-show-container">
      <%= form_for @top, :url => top_confirm_path do |f| %>

          <div class="blank">
            fill in the <span class="glyphicon glyphicon-star"></span> required info
          </div>

                <% if @top.errors.present? %>
                   <div class="alert alert-danger">
                       <ul class="test">
                         <% @top.errors.full_messages.each do |full_message| %>
                          <li>
                            <%= full_message %>
                          </li>
                          <% end %>
                       </ul>
                   </div>
                <% end %>
  
              <div class="form-group contact-us">
                <%= f.label :Name, class: "control-label" %><span class="glyphicon glyphicon-star"></span>
                <%= f.text_field :name, placeholder: 'Your name, please', class: "form-control text-code" %>
              </div>
              <div class="form-group contact-us">
                <%= f.label :Email, class: "control-label" %><span class="glyphicon glyphicon-star"></span>
                <%= f.text_field :email, placeholder: 'youremail@example.com', class: "form-control text-code" %>
              </div>
              <div class="form-group contact-us">
                <%= f.label :Message, class: "control-label" %><span class="glyphicon glyphicon-star"></span>
                <%= f.text_area :message, placeholder: "less than 50 characters", class: "form-control area-code" %>
              </div>
              
          <div class="text-center"><%= f.submit 'Confirm', class: 'btn btn-booking' %></div>
      <% end %>
      </div>
     <%= link_to "Back", :back %>
  </div>
</div>

app/views/top/confirm.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div id="inquiry" class="inquiry-header">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Contact / Confirm
    </div>
    <div class="card card-show-container">

        <%= form_for @top, :url => top_thanks_path do |f| %>
        <table class="table">
            <tr>
                <th>Name</th>
                <td>
                    <%= f.hidden_field :name %>
                    <%= @top.name %>
                </td>
            </tr>
            <tr>
                <th>EmailAddress</th>
                <td>
                    <%= f.hidden_field :email %>
                    <%= @top.email %>
                </td>
            </tr>
            <tr>
                <th>Message</th>
                <td>
                    <%= f.hidden_field :message %>
                    <%= simple_format(@top.message) %>
                </td>
            </tr>
        </table>
       <div class="text-center"><%= f.submit 'Submit', class: 'btn btn-booking' %></div>
        <% end %>
    </div>
      <div class="back"><%= link_to "Back", :back %></div>
  </div>
</div>

app/views/top/home.html.erb
<div class="top-organizer-show">
    <div class="upcoming">Organizer</div>
    <div class="top-vertical"><%= image_tag 'no-avatar.png', :class => "top-organizer-img" %><p>test</p></div>
    <div class="top-vertical"><%= image_tag 'no-avatar.png', :class => "top-organizer-img" %><p>test</p></div>
    <div class="top-vertical"><%= image_tag 'no-avatar.png', :class => "top-organizer-img" %><p>test</p></div>
</div>
    
<div class="top-events-left">
   <div class="upcoming">Upcoming events</div>
      <% @events.order('id').each do |event| %>
    
    <div class="row">
      <div class="wrap clearfix hvr-glow" data-url="<%= show_event_path(event) %>">
         <!--<div class="col-xs-12 col-md-7">-->
         <div class="left-image">
               <div id="all-events" class="trim">
                   <%#= event.image.inspect %>
                 <% if event.image.thumb.present? %>
                   <%= image_tag event.image.thumb.url , class: "img-responsive center-block" %>
                 <% end %>
               </div>
         </div>
         <!--<div class="col-xs-12 col-md-5">-->
         <div class="event-contents">
                <div class="top-events-title"><%= link_to event.title, show_event_path(event) %></div>
                    <div class="top-events-time">
                      <% if event.time || event.end_time.present? %>
                         <%= I18n.l event.date, format: :full_date if event.date.present? %>,
                           &nbsp;<%= event.time.strftime("%H:%M") %>&nbsp;~
                      <% end %>
                    </div>
                  <div class="venue-top glyphicon glyphicon-flag"><%= t '.Venue' %>:<%= event.address %></div>
                  <div class="price-top">
                    <% if event.price.blank? || event.price == 0 %>
                     <%= t '.Admission_free' %>
                    <% else %>
                     <%= number_to_currency(event.price, :precision => 0, :local => 'jp') %>&nbsp;<%= t '.at_the_door' %>
                    <% end %>
                  </div>
                <div class="event-text"><%= simple_format event.text %></div>
         </div>
      </div>
    </div><!-- row -->
      
      <% end %>
      
      <div class="top-pagination">
          <%#= link_to "test", spots_test_path %>
      </div>
      
</div><!-- top-events-left -->

<div class="row-right">
  <div class="upcoming">Blogs</div>
           <% @blogs.each_with_index do |blog| %>
           <ul>
              <li><%= link_to blog.title, show_blog_path(blog) %></li>
           </ul>
           <% end %>
</div><!-- row-right -->
    
      <script>
          jQuery('.wrap').click(function() {
              location.href = jQuery(this).attr('data-url');
          });
      </script>

app/views/top/terms_of_service.html.erb
Terms of Service

app/views/top/thanks.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div id="inquiry" class="inquiry-header">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Thank you!
    </div>
    <div class="card card-show-container">
        <div class="text-center">
            <p>Thank you for contacting us. We value your comments.</p>
        </div>
    </div>
  </div>
</div>