config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
      root to: 'top#home'
      get "about" => "top#about", as: "about"
      post 'top/confirm' => 'top#confirm' #確認画面
      post 'top/thanks' => 'top#thanks' #送信完了画面
      get "terms_of_service" => "top#terms_of_service"
      
      get 'users/me' => 'users#me'
      get '/users/:user_id/show', to: 'users#show', as: 'show_user'
      delete 'delete_users/:id' => 'users#destroy', as: :delete_user
      
      get 'events/:event_id/show', to: 'events#show', as: 'show_event'
      
      scope :organizer do
        resources :events, except: [:show, :index] do
          member do
           post 'confirm', to: 'events#confirm'
           post 'confirm2', to: 'events#confirm2'
          end
        end
        resources :timetables
      end
      
      resources :blogs, except: [:index, :show]
      get 'blogs/:blog_id/show', to: 'blogs#show', as: 'show_blog'
      
      get "organizer/blogs" => "users#blogs", as: "postblog"
      get "organizer/else" => "users#elses", as: "else"
      
      scope :admin do
        resources :events, except: [:show, :index] do
          member do
            post 'confirm2'
          end
        end
        post 'events/confirm', to: 'events#confirm'
        # post 'events/confirm2', to: 'events#confirm2'
        resources :timetables
      end
      
      get 'admin/dashboard'
      get 'admin/users'
      get 'admin/events'
      get 'admin/events/:event_id/participants', to: 'admin#participants', as: 'admin_participants'
      
      resources :events, only: [:show, :index] do
        member do
          get "ticket" => "events#ticket"
        end
        resource :bookings, only: [:create, :destroy]
        member do
          get "charge" => "bookings#charge"
          post "pay" => "bookings#pay"
        end
      end
      
  end
  
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
   #before_action :admin_check
   before_action :organizer_check
  
  def index
    @timetable = Timetable.new(event_id: params[:event_id]) 
    @timetables = Timetable.where(event_id: params[:event_id])
    @event = Event.find(params[:event_id])
  end
  
  def create
    @timetable = Timetable.new(timetable_params)
    @timetable[:event_id] = params[:event_id]
    if @timetable.save
       redirect_to timetables_path(event_id: params[:event_id])
    else
      @timetables = Timetable.where(event_id: params[:event_id])
      flash.now[:alert] = "Your column is not created yet."
      render 'index'
    end
  end
  
  def edit
    @timetable = Timetable.find(params[:id])
  end

  def update
      @timetable = Timetable.find(params[:id])
      @timetable.assign_attributes(timetable_params)
    if @timetable.update(timetable_params)
      redirect_to timetables_path(event_id: params[:event_id])
    else
      render 'edit'
    end
  end
  def destroy
    @timetable = Timetable.find(params[:id])
    @timetable.destroy
    redirect_to timetables_path(event_id: @timetable.event_id)
  end
  
  private
  def timetable_params
    params.require(:timetable).permit(:time, :description)
  end

end

app/views/timetables/_form.html.erb
<div class="form-group">
  <%= form_for(@timetable) do |f| %>
  　<input type="hidden" name="event_id" value="<%= @timetable.event_id %>">
     <% if @timetable.errors.present? %>
       <div class="alert alert-danger">
         <%= alert %>
         <ul>
             <% @timetable.errors.full_messages.each do |full_message| %>
             <li>
                 <%= full_message %>
             </li>
            <% end %>
         </ul>
       </div>
     <% end %>
 
    <div class="form-inline">
        <div class="form-group">
         <%= f.label :Time %><br />
         <%= f.text_field :time, style: "width:90px;", class: "form-control", placeholder: "00:00" %>
        </div>
        <div class="form-group">
         <%= f.label :Description %><br />
         <%= f.text_field :description, style: "width:390px;", class: "form-control", placeholder: "less than 50 characters" %>
        </div>
        <div class="form-group"><br />
          <%= f.submit 'Create', class: "btn btn-timetable" %>
        </div>
    </div>
   <% end %>
</div>

app/views/timetables/edit.html.erb
<% @page_title = 'Colum' %>

<div class="inquiry-header">Edit Columns</div>       
       
<div class='row'>
  <div class='col-sm-offset-2 col-sm-8'>
    <div class="timetable-back">

   <%= render 'form' %>

         <%= link_to "Back", :back %>

    </div>
  </div>
</div>
  

app/views/timetables/index.html.erb
<% @page_title = 'Timetable' %>

<div class="inquiry-header">Create Timetables</div>

<div class='row'>
  <div class='col-sm-offset-2 col-sm-8'>
    <div class="timetable-back">
    
        <%= render 'form' %>
          <span style="font-weight:bold">&nbsp;Timetable</span>
            <table class="table table-bordered">
                <thead>
            　　　<tr class="active">
            　　　     <th class="col-xs-1 col-ms-1 col-md-1 col-lg-1">Time</th>
            　　  　  <th class="col-xs-3 col-ms-3 col-md-4 col-lg-4">Description</th>
            　　　</tr>
                </thead>
              <% @timetables.each do |timetable| %>
                <tbody>
                    <tr>
                       <th><%= timetable.time %></th>
                       <th><%= timetable.description %></th>
                       <th class="col-xs-1 col-ms-1 col-md-1 col-lg-1 hidden1"><%= link_to "Edit", edit_timetable_path(timetable) %>&nbsp/
                       <%= link_to "Delete", timetable_path(timetable), method: :delete, data: { confirm: 'Are you sure？' } %></th>
                    </tr>
                </tbody>
              <% end %>
            </table>
        
         <%= link_to "Show Event", show_event_path(@event) %><br />
         <%= link_to "Organizer Page", users_me_path %>
      
    </div>
  </div>
</div>