config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
      root to: 'top#home'
      get "about" => "top#about", as: "about"
      post 'top/confirm' => 'top#confirm' #確認画面
      post 'top/thanks' => 'top#thanks' #送信完了画面
      get "terms_of_service" => "top#terms_of_service"
      
      get 'users/me' => 'users#me'
      get '/users/:user_id/show', to: 'users#show', as: 'show_user'
      delete 'delete_users/:id' => 'users#destroy', as: :delete_user
      
      get 'events/:event_id/show', to: 'events#show', as: 'show_event'
      
      scope :organizer do
        resources :events, except: [:show, :index] do
          member do
           post 'confirm', to: 'events#confirm'
           post 'confirm2', to: 'events#confirm2'
          end
        end
        resources :timetables
      end
      
      resources :blogs, except: [:index, :show]
      get 'blogs/:blog_id/show', to: 'blogs#show', as: 'show_blog'
      
      get "organizer/blogs" => "users#blogs", as: "postblog"
      get "organizer/else" => "users#elses", as: "else"
      
      scope :admin do
        resources :events, except: [:show, :index] do
          member do
            post 'confirm2'
          end
        end
        post 'events/confirm', to: 'events#confirm'
        # post 'events/confirm2', to: 'events#confirm2'
        resources :timetables
      end
      
      get 'admin/dashboard'
      get 'admin/users'
      get 'admin/events'
      get 'admin/events/:event_id/participants', to: 'admin#participants', as: 'admin_participants'
      
      resources :events, only: [:show, :index] do
        member do
          get "ticket" => "events#ticket"
        end
        resource :bookings, only: [:create, :destroy]
        member do
          get "charge" => "bookings#charge"
          post "pay" => "bookings#pay"
        end
      end
      
  end
  
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  
end

app/views/admin/dashboard.html.erb
<% @page_title = 'dashboard' %>

<div class="row">
  <div class='col-sm-offset-1 col-sm-10'>
      <div class="page-header" style="margin-top:-30px;padding-bottom:0px;">
        <div class="inquiry-header"><%= @page_title %></div>
      </div>
    <div class="event-back">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><%= link_to 'Dashboard', admin_dashboard_path, class: "glyphicon glyphicon-th" %></li>
          <li role="presentation"><%= link_to 'Events', admin_events_path, class: "glyphicon glyphicon-flag" %></li>
          <li role="presentation"><%= link_to 'Users', admin_users_path, class: "glyphicon glyphicon-list-alt" %></li>
        </ul>


        
    </div>
  </div>
</div>

app/views/admin/events.html.erb
<% @page_title = 'Admin' %>

<div class="row">
  <div class='col-sm-offset-1 col-sm-10'>
      <div class="page-header" style="margin-top:-30px;padding-bottom:0px;">
        <div class="inquiry-header"><%= @page_title %></div>
      </div>
    <div class="event-back">
        <ul class="nav nav-tabs">
          <li role="presentation"><%= link_to 'Dashboard', admin_dashboard_path, class: "glyphicon glyphicon-th" %></li>
          <li role="presentation" class="active"><%= link_to 'Events', admin_events_path, class: "glyphicon glyphicon-flag" %></li>
          <li role="presentation"><%= link_to 'Users', admin_users_path, class: "glyphicon glyphicon-list-alt" %></li>
        </ul>
        
    <div align="right"><%= link_to "Event Create", new_event_path, class: "btn btn-eventcreate" %></div>
      
     <% if @events.present? %>
        <table class="table">
          <tr>
             <th>id</th>
             <th>title</th>
             <th>created_at</th>
             <th>Participants</th>
             <th>Price</th>
             <th></th>
             <th></th>
          </tr>

        <% @events.order('id').each do |event| %>
          <tr>
             <td><%= event.id %></td>
             <td><%= link_to event.title, show_event_path(event) %></td>
             <td><%= event.created_at.strftime("%Y,%m/%d-%H:%M") %></td>
             <td><%= link_to ( "#{event.booking_users.count} / #{event.capacity}"), admin_participants_path(event) %></td>
             <td><% if event.price.blank? || event.price == 0 %>free
                 <% else %><%= number_to_currency(event.price, :precision => 0, :local => 'jp') %>
                 <% end %>
             </td>
             <td><%= link_to 'Timetables', timetables_path(event_id: event.id) %></td>
             <td><%= link_to "Edit", edit_event_path(event) %></td>
          </tr>
        <% end %>

        </table>
     <% else %>
        <p>no event</p>
     <% end %>
        
    </div>
  </div>
</div>

app/views/admin/participants.html.erb
<% @page_title = 'Participants' %>

<div class="row">
  <div class='col-sm-offset-1 col-sm-10'>
      <div class="page-header" style="margin-top:-30px;padding-bottom:0px;">
        <div class="inquiry-header"><%= @page_title %></div>
      </div>
    <div class="event-back">
        
     <% if @event.booking_users.present? %>
        <table class="table">
          <tr>
             <th>Id</th>
             <th>Name</th>
             <th>Email</th>
             <th>Participants</th>
             <th><% if @event.total_price.nil? %>
                  Admission free
                 <% else %>
                  Total
                 <% end %>
             </th>
             <th></th>
             <th></th>
          </tr>

         <% @booking_users.each do |user| %>
          <tr>
             <td><%= user.id %></td>
             <td><%= link_to user.name, show_user_path(user) %></td>
             <td><%= user.email %></td>
             <td><%= user.bookings.find_by(event_id: @event.id).people %></td>
                 <% people = user.bookings.find_by(event_id: @event.id).people %>
             <td><%= (people * @event.price) if @event.price.present? && people.present? %></td>
             <td>
               <%= link_to "Unbooking", event_bookings_path(@event, user_id: user.id), method: :delete, data: { confirm: "Are you sure you want to unbooking the User <strong>#{user.name}</strong>?",
               cancel: "Cancel",
               commit: "Unbooking"}, title: "Confirmation" %>
             </td>
          </tr>
         <% end %>
          <tr class="active">
             <td>Total</td>
             <td></td>
             <td></td>
             <td><%= @event.bookings.sum(:people, :conditions => "people is not null") %></td>
             <td><%= @event.total_price %></td>
             <td></td>
          </tr>
        </table>
     <% else %>
        <p>no participants</p>
     <% end %>
        
    </div>
    <div class="back"><%= link_to "Back", :back %></div>
  </div>
</div>

app/views/admin/users.html.erb
 <% @page_title = 'Admin' %>

<div class="row">
  <div class='col-sm-offset-1 col-sm-10'>
      <div class="page-header" style="margin-top:-30px;padding-bottom:0px;">
         <div class="inquiry-header"><%= @page_title %></div>
      </div>
    <div class="event-back">
        <ul class="nav nav-tabs">
          <li role="presentation"><%= link_to 'Dashboard', admin_dashboard_path, class: "glyphicon glyphicon-th" %></li>
          <li role="presentation"><%= link_to 'Events', admin_events_path, class: "glyphicon glyphicon-flag" %></li>
          <li role="presentation" class="active"><%= link_to 'Users', admin_users_path, class: "glyphicon glyphicon-list-alt" %></li>
        </ul>
      <br />
      
        <% if @users.present? %>
        <table class="table table-striped">
          <tr>
             <th>id</th>
             <th>name</th>
             <th>email</th>
             <th>profile image</th>
             <th>admin</th>
             <th>created_at</th>
             <th></th>
          </tr>

        <% @users.order('id').each do |user| %>
          <tr>
             <td><%= user.id %></td>
             <td><%= link_to user.name, show_user_path(user) %></td>
             <td><%= user.email %></td>
             <td><% if user.profile.present? && user.profile.private %>
                  Public
                 <% else %>
                  Private
                 <% end %>
             </td>
             <td><%= user.admin %></td>
             <td><%= user.created_at.strftime("%Y,%m/%d-%H:%M") %></td>
             <td>
               <%= link_to "Delete", delete_user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the User <strong>#{user.name}</strong>?",
               cancel: "Cancel",
               commit: "Delete"}, title: "Confirmation" %>
             </td>
          </tr>
        <% end %>

        </table>
     <% else %>
        <p>no user</p>
     <% end %>
        
    </div>
  </div>
</div>