config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
      root to: 'top#home'
      get "about" => "top#about", as: "about"
      post 'top/confirm' => 'top#confirm' #確認画面
      post 'top/thanks' => 'top#thanks' #送信完了画面
      get "terms_of_service" => "top#terms_of_service"
      
      get 'users/me' => 'users#me'
      get '/users/:user_id/show', to: 'users#show', as: 'show_user'
      delete 'delete_users/:id' => 'users#destroy', as: :delete_user
      
      get 'events/:event_id/show', to: 'events#show', as: 'show_event'
      
      scope :organizer do
        resources :events, except: [:show, :index] do
          member do
           post 'confirm', to: 'events#confirm'
           post 'confirm2', to: 'events#confirm2'
          end
        end
        resources :timetables
      end
      
      resources :blogs, except: [:index, :show]
      get 'blogs/:blog_id/show', to: 'blogs#show', as: 'show_blog'
      
      get "organizer/blogs" => "users#blogs", as: "postblog"
      get "organizer/else" => "users#elses", as: "else"
      
      scope :admin do
        resources :events, except: [:show, :index] do
          member do
            post 'confirm2'
          end
        end
        post 'events/confirm', to: 'events#confirm'
        # post 'events/confirm2', to: 'events#confirm2'
        resources :timetables
      end
      
      get 'admin/dashboard'
      get 'admin/users'
      get 'admin/events'
      get 'admin/events/:event_id/participants', to: 'admin#participants', as: 'admin_participants'
      
      resources :events, only: [:show, :index] do
        member do
          get "ticket" => "events#ticket"
        end
        resource :bookings, only: [:create, :destroy]
        member do
          get "charge" => "bookings#charge"
          post "pay" => "bookings#pay"
        end
      end
      
  end
  
    devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, #:timeoutable,
         :omniauthable, omniauth_providers: [:twitter, :facebook]
         
  validates :name, presence: true, length: { maximum: 50 }
  #validate :agreement_valid?
  
  has_many :events, foreign_key: "user_id", dependent: :destroy

  has_many :bookings, foreign_key: "user_id", dependent: :destroy
  has_many :booking_events, through: :bookings, source: :event
  
  has_many :blogs, foreign_key: "user_id", dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader

  def booking(event)
    bookings.find_or_create_by(event_id: event.id)
  end

  def unbooking(event)
    booking = bookings.find_by(event_id: event.id)
    booking.destroy if booking
  end

    #http://ruby-rails.hatenadiary.com/entry/20140805/1407200400
  def self.from_omniauth(auth)
    # providerとuidでUserレコードを取得する
    # 存在しない場合は、ブロック内のコードを実行して作成する
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # auth.provider には "twitter"、
      # auth.uidには twitterアカウントに基づいた個別のIDが入っている
      # first_or_createメソッドが自動でproviderとuidを設定してくれるので、
      # ここでは設定は必要ない
      user.name = auth.info.nickname # twitterで利用している名前が入る
      user.email = auth.info.email # twitterの場合入らない
    end
  end
  
  # Devise の RegistrationsController はリソースを生成する前に self.new_sith_session を呼ぶ
  # つまり、self.new_with_sessionを実装することで、サインアップ前のuserオブジェクトを初期化する
  # ときに session からデータをコピーすることができます。
  # OmniauthCallbacksControllerでsessionに値を設定したので、それをuserオブジェクトにコピーします。
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  # providerがある場合（Twitter経由で認証した）は、
  # passwordは要求しないようにする。
  def password_required?
    super && provider.blank?
  end

  # プロフィールを変更するときによばれる
  def update_with_password(params, *options)
    # パスワードが空の場合
    if encrypted_password.blank?
      # パスワードがなくても更新できる
      update_attributes(params, *options)
    else
      super
    end
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  private
    #def agreement_valid?
    #  errors.add(:agreement, 'していただかない場合は、登録できません。') unless agreement == true
    #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :sign_in_required
   #before_action :admin_check, only: [:show, :destroy]
   before_action :organizer_check, only: [:show, :organizer, :blogs, :destroy]
   #before_action :authenticate_user!
  
  def me
      @users = User.all
  end
  
  def show
    @user = User.find(params[:user_id])
    @booking = current_user.booking(@event)
  end
  
  def blogs
  end
  
  def elses
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'It has been successfully cancelled.'
    redirect_to admin_users_url
  end

end

app/views/users/_me_side.html.erb
  <aside class="me-aside">
      <div class="my_profiles">
          <% if current_user.organizer? %>
             <%= t '.Organizer_profile' %>
          <% else %>
             <%= t '.My_profile' %>
          <% end %>
      </div>
      <table class="table">
            <div class="text-center">
              <% if current_user.avatar? %>
                <%= image_tag(current_user.avatar.thumb.url, :class => "mypage_img") %>
              <% else %>
                <%= image_tag 'no-avatar.png', width: 200, :class => "mypage_img"%>
              <% end %>
            </div>
        <div align="right"><%= link_to 'Edit', edit_user_registration_path %></div>
        
          <tr>
            <% if current_user.organizer? %>
              <th><%= t '.Organizer_name' %></th>
            <% else %>
              <th><%= t '.User_name' %></th>
            <% end %>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <th><%= t '.Email_address' %></th>
            <td><%= current_user.email %></td>
          </tr>
       <% if current_user.avatar.present? %>
          <tr>
            <th><%= t '.Profile-Image_status' %></th>
            <td>
              <% if current_user.private %>
              <%# if current_user.profile.present? && current_user.profile.private %>
                <%= t '.Public' %>
              <% else %>
                <%= t '.Private' %>
              <% end %>
            </td>
          </tr>
       <% end %>
       <% if current_user.organizer? %>
          <tr>
            <th><%= t '.Sentence' %></th>
            <td><%= current_user.sentence %></td>
          </tr>
       <% end %>
          <tr><th><td></td></th></tr>
      </table>
  </aside>

app/views/users/_my_events.html.erb
<div class="my_events"><%= t '.My_Booking_Events' %></div>
              <hr>
            <% current_user.booking_events.each_with_index do |event, i| %>
                     <div class="my-event-pic">
                       <% if event.image? %>
                          <%= image_tag event.image.thumb.url, :class => "mypage_event_img" %>
                       <% else %>
                          <%= image_tag 'noimage.gif', :class => "mypage_event_img" %>
                       <% end %>
                     </div>
                <div class="me-event">
                   <div class="me-event-title"><%= link_to event.title, show_event_path(event) %></div>
                      <div class="me-event-time">
                        <% if event.time || event.end_time.present? %>
                           <%= I18n.l event.date, format: :full_date if event.date.present? %>,&nbsp;<%= event.time.strftime("%H:%M") %>&nbsp;~&nbsp;
                             <% if (event.date.present? && event.end_date.present?) && (event.date != event.end_date) %>
                               <%= I18n.l event.end_date, format: :full_date %>,
                             <% end %>
                            <%= event.end_time.strftime("%H:%M") if event.end_time.present? %>
                        <% end %>
                      </div>
                    <div class="me-other">
                      <span style="font-weight:bold"><%= t '.Booking_people' %></span>
                      :&nbsp;<%= current_user.bookings[i].people if current_user.bookings[i].people.present? %><br />
                      <span style="font-weight:bold"><%= t '.Confirmatin_number' %></span>
                      :&nbsp;<%= current_user.bookings[i].number if current_user.bookings[i].number.present? %><br />
                    </div>
                      <%= link_to "unbooking", event_bookings_path(event, user_id: current_user.id), method: :delete, data: { confirm: 'Are you really unbooking the event registration？',
                      cancel: "Cancel",
                      commit: "Unbooking"}, title: "Confirmation", class: "btn btn-unbooking" %>
                </div>
                 <hr>
            <% end %>
                <%= "No booking event" if !current_user.booking_events.present? %>
           <div class="all-events"><%= link_to "all events", root_path(anchor: 'all-events'), class: "all-events" %></div>

app/views/users/blogs.html.erb
    <%  @page_title = "Blogs" %>

<div class="inquiry-header"><%= @page_title %></div>

<div class="card card-mypage-container">

<%= render 'me_side' %>
      
  <div class="me-right">
          <ul class="nav nav-tabs">
            <li role="presentation"><%= link_to 'Events', users_me_path, class: "glyphicon glyphicon-flag" %></li>
            <li role="presentation" class="active"><%= link_to 'Blogs', postblog_path, class: "glyphicon glyphicon-list-alt" %></li>
            <li role="presentation"><%= link_to 'else', else_path, class: "glyphicon glyphicon-th" %></li>
          </ul>
                
            <div align="right"><%= link_to "Blogs Create", new_blog_path, class: "btn btn-eventcreate" %></div>
       <% if current_user.blogs.present? %>
               <% current_user.blogs.each_with_index do |blog| %>
                     <div class="">
                       <% if blog.photo? %>
                          <%= image_tag blog.photo.thumb.url, :class => "mypage_event_img" %>
                       <% else %>
                          <%= image_tag 'noimage.gif', :class => "mypage_event_img" %>
                       <% end %>
                     </div>
                        <%= blog.title %>
                        <%= blog.text %>
                        <%= link_to "Edit", edit_blog_path(blog) %>
                        <%= link_to "Delete", blog_path(blog), method: :delete, data: { confirm: 'Are you sure？' } %>
               <% end %>
       <% else %>
          no blogs</br>
       <% end %>
          
          <hr>
          
          <%= link_to 'Organizer Top Page', users_me_path %>
          
  </div><!-- /me-right -->
</div><!-- /card-container -->

app/views/users/booking_events.html.erb
    <%  @page_title = "BookingEvents" %>

<div class="inquiry-header"><%= @page_title %></div>

<div class="card card-mypage-container">

<%= render 'me_side' %>
      
  <div class="me-right">
          <ul class="nav nav-tabs">
            <li role="presentation"><%= link_to 'Events', users_me_path, class: "glyphicon glyphicon-flag" %></li>
            <li role="presentation"><%= link_to 'Blogs', blogs_path, class: "glyphicon glyphicon-list-alt" %></li>
            <li role="presentation" class="active"><%= link_to 'BookingEvents', booking_events_path, class: "glyphicon glyphicon-list-alt" %></li>
          </ul>
                
          
          <%= render 'my_events' %>
          
  </div><!-- /me-right -->
</div><!-- /card-container -->

app/views/users/elses.html.erb
    <%  @page_title = "Else" %>

<div class="inquiry-header"><%= @page_title %></div>

<div class="card card-mypage-container">

<%= render 'me_side' %>
      
  <div class="me-right">
          <ul class="nav nav-tabs">
            <li role="presentation"><%= link_to 'Events', users_me_path, class: "glyphicon glyphicon-flag" %></li>
            <li role="presentation"><%= link_to 'Blogs', postblog_path, class: "glyphicon glyphicon-list-alt" %></li>
            <li role="presentation" class="active"><%= link_to 'else', else_path, class: "glyphicon glyphicon-th" %></li>
          </ul>
                
          
          else</br>
          
          <%= link_to 'Organizer Top Page', users_me_path %>
          
  </div><!-- /me-right -->
</div><!-- /card-container -->

app/views/users/me.html.erb
<% if current_user.organizer? %>
    <% @page_title = "Organizer page" %>
<% else %>
    <%  @page_title = "My page" %>
<% end %>

<div class="inquiry-header"><%= @page_title %></div>

<div class="card card-mypage-container">
        
        <%= render 'me_side' %>
              
          <div class="me-right">
             <% if current_user.organizer? %>
                        <ul class="nav nav-tabs">
                          <li role="presentation" class="active"><%= link_to 'Events', users_me_path, class: "glyphicon glyphicon-flag" %></li>
                          <li role="presentation"><%= link_to 'Blogs', postblog_path, class: "glyphicon glyphicon-list-alt" %></li>
                          <li role="presentation"><%= link_to 'else', else_path, class: "glyphicon glyphicon-th" %></li>
                        </ul>
                        
                        <div align="right"><%= link_to "Event Create", new_event_path, class: "btn btn-eventcreate" %></div>
                  
                  <% if current_user.events.present? %>
                  
                     <table class="table">
                          <tr>
                             <th>title</th>
                             <th></th>
                             <th></th>
                             <th>created_at</th>
                          </tr>
                              
                        <% current_user.events.each_with_index do |event| %>
                          <tr>
                             <td><%= link_to event.title, show_event_path(event) %></td>
                             <td><%= link_to 'Timetables', timetables_path(event_id: event.id) %></td>
                             <td><%= link_to "Edit", edit_event_path(event) %></td>
                             <td><%= event.created_at.strftime("%Y, %m/%d - %H:%M") %></td>
                          </tr>
                        <% end %>
                     </table>
                  <% else %>
                        <p>no event</p>
                  <% end %>
             <% else %>
             
                 <%= render 'my_events' %>
                
             <% end %>  
          </div><!-- /me-right -->
</div><!-- /card-container -->

app/views/users/show.html.erb
<%  @page_title = "User page" %>

<h1><span style="color:#fff;"><%= @page_title %></span></h1>

<div class="event-back">
  <div class='row'>
    <div class='col-sm-offset-3 col-sm-6'>
   　  <table class="table">
          <div class="text-center">
            <% if @user.avatar? %>
              <%= image_tag(@user.avatar.thumb.url, :class => "img-circle") %>
            <% else %>
              <%= image_tag 'no-avatar.png', width: 200, :class => "img-circle"%>
            <% end %>
          </div>
      
        <tr>
          <th><%= t '.User_name' %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th><%= t '.Email_address' %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>Profile-Image status</th>
          <td>
            <% if @user.private %>
            <%# if @user.profile.present? && @user.profile.private %>
              Public
            <% else %>
              Private
            <% end %>
          </td>
        </tr>
        <tr><th><td></td></th></tr>
      </table>
          <span style="font-weight:bold"><%= t '.My_events' %></span><br />
            <% current_user.booking_events.each_with_index do |event, i| %>
              <% if (event.date.present? && event.time.present?) %>
                <span style="margin-left:20px"><%= I18n.l event.date, format: :full_date %></span>
                 ,&nbsp;<%= event.time.strftime("%H:%M") %>~
              <% end %><br />
              <div class="me-event">
                <% if event.image? %>
                    <%= image_tag event.image.thumb.url, :class => "e-img-mini" %>
                <% else %>
                    <%= image_tag 'noimage.gif', :class => "e-img-mini" %>
                <% end %>
                <%= link_to event.title, show_event_path(event) %><br />
                <span style="font-weight:bold"><%= t '.Confirmatin_number' %></span><%= current_user.bookings[i].number if current_user.bookings[i].number.present? %><br />
                <span style="font-weight:bold"><%= t '.Booking_people' %></span><%= current_user.bookings[i].people if current_user.bookings[i].people.present? %><br />
              </div>
              <hr>
            <% end %>
       <div class="back"><%= link_to "Back", :back %></div>
    </div>
  </div>
</div>